# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import numpy
import numpy.typing
import typing
__all__ = [
    "Annotation",
    "EdfFile",
    "Signal",
]

@typing.final
class Annotation:
    r"""
    A single annotation from the EDF+ file.
    """
    @property
    def onset(self) -> builtins.float: ...
    @property
    def duration(self) -> typing.Optional[builtins.float]: ...
    @property
    def text(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class EdfFile:
    r"""
    An open EDF/EDF+ file.
    """
    @property
    def num_signals(self) -> builtins.int: ...
    @property
    def num_records(self) -> builtins.int: ...
    @property
    def record_duration(self) -> builtins.float: ...
    @property
    def duration(self) -> builtins.float: ...
    @property
    def variant(self) -> builtins.str: ...
    @property
    def patient_id(self) -> builtins.str: ...
    @property
    def recording_id(self) -> builtins.str: ...
    @property
    def start_datetime(self) -> typing.Any:
        r"""
        Returns `datetime.datetime` if the header date/time could be parsed,
        or a string like `"04.04.yy 12.57.02"` if it was anonymized.
        """
    @property
    def patient_name(self) -> typing.Optional[builtins.str]: ...
    @property
    def patient_code(self) -> typing.Optional[builtins.str]: ...
    @property
    def patient_sex(self) -> typing.Optional[builtins.str]: ...
    @property
    def patient_birthdate(self) -> typing.Optional[typing.Any]:
        r"""
        Returns `datetime.date` if parseable, a raw string if anonymized, or `None` if absent.
        """
    @property
    def patient_additional(self) -> typing.Optional[builtins.str]: ...
    @property
    def admin_code(self) -> typing.Optional[builtins.str]: ...
    @property
    def technician(self) -> typing.Optional[builtins.str]: ...
    @property
    def equipment(self) -> typing.Optional[builtins.str]: ...
    @property
    def recording_additional(self) -> typing.Optional[builtins.str]: ...
    @property
    def annotations(self) -> builtins.list[Annotation]: ...
    @property
    def warnings(self) -> builtins.list[builtins.str]: ...
    @property
    def header(self) -> dict: ...
    def __new__(cls, path: builtins.str) -> EdfFile: ...
    def __enter__(self, slf: EdfFile) -> EdfFile: ...
    def __exit__(self, *_args: typing.Any) -> None: ...
    def __repr__(self) -> builtins.str: ...
    def signal(self, idx_or_label: typing.Any) -> Signal:
        r"""
        Get a signal by index or label.
        """
    def ordinary_signal_indices(self) -> builtins.list[builtins.int]:
        r"""
        Indices of all non-annotation (ordinary) signals.
        """
    def read_page(self, start_sec: builtins.float, end_sec: builtins.float, signal_indices: typing.Optional[typing.Sequence[builtins.int]] = None) -> builtins.list[numpy.typing.NDArray[numpy.float64]]:
        r"""
        Read a page of physical data for multiple signals over a time range.
        
        Returns a list of numpy arrays, one per signal. Signals with different
        sample rates will produce arrays of different lengths.
        
        If `signal_indices` is None, reads all ordinary (non-annotation) signals.
        """
    def read_page_digital(self, start_sec: builtins.float, end_sec: builtins.float, signal_indices: typing.Optional[typing.Sequence[builtins.int]] = None) -> builtins.list[numpy.typing.NDArray[numpy.int16]]:
        r"""
        Read a page of digital (raw int16) data for multiple signals over a time range.
        
        If `signal_indices` is None, reads all ordinary (non-annotation) signals.
        """

@typing.final
class Signal:
    r"""
    Proxy view of a single signal, supporting numpy-style indexing.
    """
    @property
    def label(self) -> builtins.str: ...
    @property
    def transducer(self) -> builtins.str: ...
    @property
    def physical_dimension(self) -> builtins.str: ...
    @property
    def prefiltering(self) -> builtins.str: ...
    @property
    def sample_rate(self) -> builtins.float: ...
    @property
    def samples_per_record(self) -> builtins.int: ...
    @property
    def physical_min(self) -> builtins.float: ...
    @property
    def physical_max(self) -> builtins.float: ...
    @property
    def digital_min(self) -> builtins.int: ...
    @property
    def digital_max(self) -> builtins.int: ...
    @property
    def num_samples(self) -> builtins.int: ...
    def __len__(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...
    def __getitem__(self, key: typing.Any) -> typing.Any:
        r"""
        Supports `s[i]`, `s[start:stop]`, and `s[start:stop:step]`.
        """
    def to_numpy(self) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Return the entire signal as a float64 numpy array.
        """
    def to_digital(self) -> numpy.typing.NDArray[numpy.int16]:
        r"""
        Return the entire signal as a raw int16 numpy array.
        """
    def times(self) -> numpy.typing.NDArray[numpy.float64]:
        r"""
        Return timestamps (in seconds) for each sample.
        """

