"""Async API for edfarray. Hand-authored stubs (not auto-generated)."""

from __future__ import annotations

from typing import Any, Awaitable
import datetime

from edfarray._core import Annotation


class EdfFile:
    @property
    def num_signals(self) -> int: ...
    @property
    def num_records(self) -> int: ...
    @property
    def record_duration(self) -> float: ...
    @property
    def duration(self) -> float: ...
    @property
    def variant(self) -> str: ...
    @property
    def patient_id(self) -> str: ...
    @property
    def recording_id(self) -> str: ...
    @property
    def start_datetime(self) -> datetime.datetime | str: ...
    @property
    def patient_name(self) -> str | None: ...
    @property
    def patient_code(self) -> str | None: ...
    @property
    def patient_sex(self) -> str | None: ...
    @property
    def patient_birthdate(self) -> datetime.date | str | None: ...
    @property
    def patient_additional(self) -> str | None: ...
    @property
    def admin_code(self) -> str | None: ...
    @property
    def technician(self) -> str | None: ...
    @property
    def equipment(self) -> str | None: ...
    @property
    def recording_additional(self) -> str | None: ...
    @property
    def annotations(self) -> list[Annotation]: ...
    @property
    def warnings(self) -> list[str]: ...
    @property
    def annotations_ready(self) -> bool: ...
    @property
    def scan_progress(self) -> tuple[int, int]: ...
    @property
    def closed(self) -> bool: ...

    def annotations_before(self, t: float) -> list[Annotation]: ...
    def annotations_after(self, t: float) -> list[Annotation]: ...
    def annotations_in_range(self, start: float, end: float) -> list[Annotation]: ...
    def filter_annotations(self, query: str, regex: bool = False) -> list[Annotation]: ...
    def annotations_by_text(self, text: str) -> list[Annotation]: ...
    def find_all_signals(self, label: str, exact: bool = False) -> list[int]: ...
    def signal_labels(self) -> list[str]: ...
    def ordinary_signal_indices(self) -> list[int]: ...
    def signal_indices_by_rate(self) -> dict[float, list[int]]: ...
    def header(self) -> dict[str, Any]: ...
    def close(self) -> None: ...

    def wait_for_annotations(self) -> Awaitable[None]: ...
    async def __aenter__(self) -> EdfFile: ...
    async def __aexit__(self, *args: Any) -> None: ...


async def open(path: str) -> EdfFile: ...
async def inspect(path: str) -> dict[str, Any]: ...
