"""Async API for edfarray. Hand-authored stubs (not auto-generated)."""

from __future__ import annotations

from typing import Any, Awaitable
import datetime

import numpy as np
import numpy.typing as npt

from edfarray._core import Annotation


class WriterSignal:
    def __init__(
        self,
        label: str,
        physical_dimension: str,
        physical_min: float,
        physical_max: float,
        digital_min: int,
        digital_max: int,
        samples_per_record: int,
        transducer: str = "",
        prefiltering: str = "",
        reserved: str = "",
    ) -> None: ...
    def __repr__(self) -> str: ...


class EdfFile:
    @property
    def num_signals(self) -> int: ...
    @property
    def num_records(self) -> int: ...
    @property
    def record_duration(self) -> float: ...
    @property
    def duration(self) -> float: ...
    @property
    def variant(self) -> str: ...
    @property
    def patient_id(self) -> str: ...
    @property
    def recording_id(self) -> str: ...
    @property
    def start_datetime(self) -> datetime.datetime | str: ...
    @property
    def patient_name(self) -> str | None: ...
    @property
    def patient_code(self) -> str | None: ...
    @property
    def patient_sex(self) -> str | None: ...
    @property
    def patient_birthdate(self) -> datetime.date | str | None: ...
    @property
    def patient_additional(self) -> str | None: ...
    @property
    def admin_code(self) -> str | None: ...
    @property
    def technician(self) -> str | None: ...
    @property
    def equipment(self) -> str | None: ...
    @property
    def recording_additional(self) -> str | None: ...
    @property
    def annotations(self) -> list[Annotation]: ...
    @property
    def warnings(self) -> list[str]: ...
    @property
    def annotations_ready(self) -> bool: ...
    @property
    def scan_progress(self) -> tuple[int, int]: ...
    @property
    def closed(self) -> bool: ...

    def annotations_before(self, t: float) -> list[Annotation]: ...
    def annotations_after(self, t: float) -> list[Annotation]: ...
    def annotations_in_range(self, start: float, end: float) -> list[Annotation]: ...
    def filter_annotations(self, query: str, regex: bool = False) -> list[Annotation]: ...
    def annotations_by_text(self, text: str) -> list[Annotation]: ...
    def find_all_signals(self, label: str, exact: bool = False) -> list[int]: ...
    def signal_labels(self) -> list[str]: ...
    def ordinary_signal_indices(self) -> list[int]: ...
    def signal_indices_by_rate(self) -> dict[float, list[int]]: ...
    def header(self) -> dict[str, Any]: ...
    def close(self) -> None: ...

    def wait_for_annotations(self) -> Awaitable[None]: ...
    def read_page(
        self,
        start_sec: float,
        end_sec: float,
        signal_indices: list[int] | None = None,
        use_time: bool = False,
    ) -> Awaitable[list[npt.NDArray[np.float64]]]: ...
    def read_page_digital(
        self,
        start_sec: float,
        end_sec: float,
        signal_indices: list[int] | None = None,
        use_time: bool = False,
    ) -> Awaitable[list[npt.NDArray[np.int32]]]: ...
    def signal(self, idx_or_label: int | str, cache_capacity: int = 0) -> Signal: ...
    def array_proxy(self, signal_indices: list[int] | None = None) -> ArrayProxy: ...
    def write_to(self, path: str, variant: str | None = None) -> Awaitable[None]: ...

    async def __aenter__(self) -> EdfFile: ...
    async def __aexit__(self, *args: Any) -> None: ...


class Signal:
    @property
    def label(self) -> str: ...
    @property
    def transducer(self) -> str: ...
    @property
    def physical_dimension(self) -> str: ...
    @property
    def prefiltering(self) -> str: ...
    @property
    def sample_rate(self) -> float: ...
    @property
    def samples_per_record(self) -> int: ...
    @property
    def physical_min(self) -> float: ...
    @property
    def physical_max(self) -> float: ...
    @property
    def digital_min(self) -> int: ...
    @property
    def digital_max(self) -> int: ...
    @property
    def num_samples(self) -> int: ...

    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

    def read_physical(self, start: int, stop: int) -> Awaitable[npt.NDArray[np.float64]]: ...
    def read_digital(self, start: int, stop: int) -> Awaitable[npt.NDArray[np.int32]]: ...
    def read_at(self, start_sec: float, end_sec: float) -> Awaitable[npt.NDArray[np.float64]]: ...
    def to_numpy(self) -> Awaitable[npt.NDArray[np.float64]]: ...
    def to_digital(self) -> Awaitable[npt.NDArray[np.int32]]: ...
    def times(self) -> Awaitable[npt.NDArray[np.float64]]: ...


class ArrayProxy:
    @property
    def shape(self) -> tuple[int, int]: ...
    @property
    def sample_rate(self) -> float: ...
    @property
    def signal_indices(self) -> list[int]: ...

    def __repr__(self) -> str: ...

    def read_physical(
        self,
        sample_start: int,
        sample_stop: int,
        signal_indices: list[int] | None = None,
    ) -> Awaitable[npt.NDArray[np.float64]]: ...
    def read_digital(
        self,
        sample_start: int,
        sample_stop: int,
        signal_indices: list[int] | None = None,
    ) -> Awaitable[npt.NDArray[np.int32]]: ...
    def get(self, signal_idx: int, sample_idx: int) -> Awaitable[float]: ...
    def read_signals_at_sample(
        self,
        sample_idx: int,
        signal_indices: list[int] | None = None,
    ) -> Awaitable[npt.NDArray[np.float64]]: ...


async def open(path: str) -> EdfFile: ...
async def inspect(path: str) -> dict[str, Any]: ...


class EdfWriter:
    @classmethod
    async def create(
        cls,
        path: str,
        *,
        variant: str,
        record_duration: float,
        signals: list[WriterSignal],
        start_datetime: datetime.datetime | None = None,
        patient_id: str | None = None,
        recording_id: str | None = None,
        annotation_bytes_per_record: int | None = None,
    ) -> EdfWriter: ...

    def add_annotation(self, annotation: Annotation) -> None: ...
    def write_record(
        self,
        physical: list[npt.NDArray[np.float64]],
        annotations: list[Annotation] | None = None,
    ) -> Awaitable[None]: ...
    def finish(self) -> Awaitable[None]: ...
    async def __aenter__(self) -> EdfWriter: ...
    async def __aexit__(self, *args: Any) -> None: ...


async def write_edf(
    path: str,
    *,
    variant: str,
    record_duration: float,
    signals: list[WriterSignal],
    data: list[npt.NDArray[np.float64]],
    annotations: list[Annotation] | None = None,
    start_datetime: datetime.datetime | None = None,
    patient_id: str | None = None,
    recording_id: str | None = None,
    annotation_bytes_per_record: int | None = None,
) -> None: ...
